import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const snPro = localFont({
  src: [
    {
      path: "../public/fonts/snpro/snpro-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/snpro/snpro-medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/snpro/snpro-semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/snpro/snpro-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-snpro",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${snPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
